src/Entity/Player.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PlayerRepository")
 */
class Player
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="integer")
     */
    private $age;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Team", inversedBy="players")
     */
    private $team_id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Sport", inversedBy="relation")
     */
    private $sport;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getTeamId(): ?Team
    {
        return $this->team_id;
    }

    public function setTeamId(?Team $team_id): self
    {
        $this->team_id = $team_id;

        return $this;
    }

    public function getSport(): ?Sport
    {
        return $this->sport;
    }

    public function setSport(?Sport $sport): self
    {
        $this->sport = $sport;

        return $this;
    }

    public function __toString()
	{
		return $this->lastname.' '.$this->firstname;
	}
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ path('home') }}">LaboSymf</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ path('home') }}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('fos_user_registration_register') }}">New User</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Player</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{{ path('add_player') }}">Create</a>
                        <a class="dropdown-item" href="{{ path('player') }}">List</a>
                    </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Team</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{{ path('add_team') }}">Create</a>
                            <a class="dropdown-item" href="{{ path('list_team') }}">List</a>
                        </div>
                    </li>
                    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
                        <li class="nav-item">
                            <a class="nav-link disabled" href="{{ path('fos_user_security_logout') }}">
                                Logout
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link disabled" href="{{ path('fos_user_security_login') }}">
                                Login
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <div class="container">
        {% block body %} Damn {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/getAllPlayers.html.twig
{% extends 'base.html.twig' %}

{% block title %} Players {% endblock %}

{% block body %}
    <div class="container">
        Liste des players :
        <hr>
        <ul>
            {% for player in players %}
                <li>{{ player.id }}</li>
                <li>{{ player.lastname }}</li>
                <li>{{ player.firstname }}</li>
                <li>{{ player.age }}</li>
                <li>Equipe : {{ player.teamId.name }}</li>
                <a href="{{ path('delete_player', {'id': player.id}) }}">
                    <button class="btn btn-danger">
                        Delete
                    </button>
                </a>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} YES {% endblock %}

{% block body %}
    <div class="container mt-4">
     <h1>Hello {{ name }} !</h1>
    </div>
{% endblock %}

templates/index_name.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Home : {{ name }}
{% endblock %}

{% block body %}
    <div class="container">
        {{ parent() }}
        re bonjour {{ name | upper }} t'es toujours aussi beau !
    </div>
{% endblock %}

templates/list_team.html.twig
{% extends 'base.html.twig' %}

{% block title %} Team {% endblock %}

{% block body %}
    <div class="container">
        Liste des Teams :
        <hr>
        <ul>
            {% for team in teams %}
                <li>{{ team.id }}</li>
                <li>{{ team.name }}</li>
                <a href="{{ path('delete_team', {'id': team.id}) }}">
                    <button class="btn btn-danger">
                        Delete
                    </button>
                </a>
            {% endfor %}
        </ul>
    </div>
{% endblock %}